services:

  #
  # A SQL database used by the Curity Identity Server
  #
  curity-data:
    image: postgres:latest
    hostname: dbserver
    volumes:
      - ./data-backup.sql:/docker-entrypoint-initdb.d/data-backup.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password1'
      POSTGRES_DB: 'idsvr'

  #
  # A standalone instance of the Curity Identity Server
  #
  curity-idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    hostname: curityserver
    ports:
     - 6749:6749
     - 8443:8443
    volumes:
     - ./license.json:/opt/idsvr/etc/init/license/license.json
     - ./base-config.xml:/opt/idsvr/etc/init/base-config.xml
     - ./devops-dashboard.xml:/opt/idsvr/etc/init/devops-dashboard.xml
     - ./messages/attribute-prompt:/opt/idsvr/usr/share/messages/overrides/en/authentication-action/attribute-prompt/messages
     - ./customizations/htmlform.vm:/opt/idsvr/usr/share/templates/overrides/authenticator/html-form/authenticate/get.vm
    environment:
      PASSWORD: 'Password1'
      RUNTIME_PROTOCOL: "${RUNTIME_PROTOCOL}"
      RUNTIME_BASE_URL: "${RUNTIME_BASE_URL}"
