version: '3.8'
services:

  #
  # A SQL database used by the Curity Identity Server
  #
  curity-data:
    image: postgres:13.2
    hostname: dbserver
    volumes:
      - ./data-backup.sql:/docker-entrypoint-initdb.d/data-backup.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password1'
      POSTGRES_DB: 'idsvr'

  #
  # A standalone instance of the Curity Identity Server
  #
  curity-idsvr:
    # TODO: set back to latest before release
    #image: curity.azurecr.io/curity/idsvr:latest
    image: curity/idsvr-unstable:8.7.0-c56cf227cc
    hostname: curityserver
    ports:
     - 6749:6749
     - 8443:8443
    volumes:
     - ./license.json:/opt/idsvr/etc/init/license/license.json
     - ./base-config.xml:/opt/idsvr/etc/init/config.xml
     - ./messages/attribute-prompt:/opt/idsvr/usr/share/messages/overrides/en/authentication-action/attribute-prompt/messages
    environment:
      PASSWORD: 'Password1'
      RUNTIME_PROTOCOL: "${RUNTIME_PROTOCOL}"
      RUNTIME_BASE_URL: "${RUNTIME_BASE_URL}"
